version: "3.8"

services:
  sermulher-observatorio:
    build: .
    container_name: sermulher_observatorio
    restart: always
    ports:
      - "3003:3000"
    networks:
      - portainer_default
      - sermulher_network

networks:
  portainer_default:
    external: true
  sermulher_network:
    external: true
